added Dockerfile, docker-compose.yml, .env file
IhorKalaur/BookStore pull request #11
Opened 2023-09-27 17:07 UTC by IhorKalaur

2023-09-27 19:41 UTC, irynamekh approved these changes
Good job)

2023-09-28 07:20 UTC, nacenik requested changes
GJ, Let's add some improvements

2023-09-28 07:20 UTC, nacenik commented on .env
> +DEBUG_PORT=5005
don't forget about empty line

2023-09-28 07:20 UTC, nacenik commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
empty line

2023-09-28 08:03 UTC, nacenik approved these changes
GJ! :)

2023-09-28 08:19 UTC, merged