added user and roles model
IhorKalaur/BookStore pull request #7
Opened 2023-09-10 10:32 UTC by IhorKalaur

2023-09-13 18:53 UTC, AntonZhdanov commented
Good solution. Check some minor mistakes.

2023-09-15 12:26 UTC, andrii-hoienko requested changes
Nice, but some improvements required

2023-09-15 12:26 UTC, andrii-hoienko commented on pom.xml
> +            <version>1.9.4</version>
It is better to use properties for each version tag, like you did with jjwt-jackson, io.jsonwebtoken etc

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/controller/AuthenticationController.java
> +    public UserLoginResponseDto login(@RequestBody UserLoginRequestDto requestDto) {
Add @Valid annotation, to make validation work

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
What if this will be null? Is it valid case?

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/exceptions/GlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
It is better to create something like ErrorResponseDto instead of using map

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/model/User.java
> +    @Column(name = "shipping_address ")
```suggestion
    @Column(name = "shipping_address")
```

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
Please make this method work without query annotation

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/CustomUserDetailsService.java
> +                        "Can't find user by email: " + username));
cant find by email or by username?

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(INDEX_OF_BEGINNING_TOKEN_VALUE);
```suggestion
            return bearerToken.substring(TOKEN_NAME.length);
```

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/security/JwtUtil.java
> +
```suggestion
```

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/validator/FieldMatchValidator.java
> +    private String firstFieldName;
names like first and second do not contain any context, for me it is not clear what first and second  means, please choose more suitable names for this fields

2023-09-15 12:26 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/05-create-users_roles-table.yaml
> +                    referencedColumnNames: id
Please add empty lines in the end of each file

2023-09-18 12:15 UTC, andrii-hoienko approved these changes
GJ!

2023-09-18 19:29 UTC, merged