Category
IhorKalaur/BookStore pull request #8
Opened 2023-09-13 20:14 UTC by IhorKalaur

2023-09-18 15:13 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-18 15:13 UTC, vovasalyha commented on src/main/java/com/example/bookstore/exceptions/GlobalExceptionHandler.java
> +                "EntityNotFoundException",
IMO exposing your internal exception to the user is redundant from different aspects

2023-09-18 15:13 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/08-create-books-categories-table.yaml
> +            columns:
add also constraint primary key (book_id, category_id)

2023-09-22 12:07 UTC, andrii-hoienko approved these changes
GJ

2023-09-24 21:35 UTC, merged