created Entity ShoppingCart, CartItem and created tables for this Ent…
IhorKalaur/BookStore pull request #9
Opened 2023-09-17 17:49 UTC by IhorKalaur

…ities

2023-09-19 14:14 UTC, Denis-Balako requested changes
Good solution! Let's improve it!

2023-09-19 14:14 UTC, Denis-Balako commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +        return shoppingCartService.addCartItem(addRequestDto);
Don't complicate your naming. Just use "add", "update", etc. without type name in it

2023-09-19 14:14 UTC, Denis-Balako commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +    @Operation(summary = "create new cart item",
Start with a capital letter. Let your doc be nice 😄

2023-09-19 14:14 UTC, Denis-Balako commented on src/main/java/com/example/bookstore/dto/shopping/cart/ShoppingCartDto.java
> +    private String userName;
We should return userId instead of username 🤔

2023-09-19 14:14 UTC, Denis-Balako commented on src/main/java/com/example/bookstore/dto/cart/item/CartItemDto.java
> +    private Long shoppingCartId;
Optional: You're returning the value, that user already knows (types in URL path). To my mind, it makes your code a little complicated, and you can just use CartItemDtoWithoutShoppingCartId for returning value always.

2023-09-19 14:14 UTC, Denis-Balako commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
Use FetchType.LAZY

2023-09-19 14:14 UTC, Denis-Balako commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
also make columns nullable = false

2023-09-19 14:14 UTC, Denis-Balako commented on src/main/java/com/example/bookstore/model/ShoppingCart.java
> +    @OneToOne
Use FetchType.LAZY

2023-09-19 14:14 UTC, Denis-Balako commented on src/main/java/com/example/bookstore/model/ShoppingCart.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shoppingCart")
OneToMany relation has FetchType.LAZY by default

2023-09-22 12:31 UTC, andrii-hoienko requested changes
GJ, I left minor comments

2023-09-22 12:31 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
Better to add this method to user service, it is rather user service responsibility to get user

2023-09-22 12:31 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/dto/shopping/cart/ShoppingCartDto.java
> +    private String userName;
agree

2023-09-25 15:50 UTC, vovasalyha approved these changes

2023-09-26 15:05 UTC, merged